Implement Feature: /colorcode
RedstoneTools/redstone-tools pull request #59
Opened 2023-02-16 21:43 UTC by orbyfied

2023-02-16 21:59 UTC, orbyfied commented
dont merge yet

2023-02-16 21:59 UTC, orbyfied commented
there are bugs

2023-02-16 22:09 UTC, orbyfied commented
Its complete now, all bugs eliminated
@Matthias1590 you can merge

2023-02-16 22:20 UTC, Matthias1590 requested changes

2023-02-16 22:21 UTC, orbyfied commented on src/main/java/com/domain/redstonetools/features/commands/colorcode/ColorCodeFeature.java
> +@Feature(name = "colorcode")
In the document it says just `colorcode`, only r-stack has another `/` but sure.

2023-02-16 22:23 UTC, orbyfied commented on src/main/java/com/domain/redstonetools/utils/CharTreeNode.java
> +package com.domain.redstonetools.utils;
This is much more performant than multiple `endsWith` calls, which is very useful as we are doing `endsWith` on a block ID with 5 strings every block in the selection every single time the command was run.

In my opinion, this optimization is relatively needed.
I'd prefer to keep it.

2023-02-16 22:27 UTC, Matthias1590 commented on src/main/java/com/domain/redstonetools/utils/CharTreeNode.java
> +package com.domain.redstonetools.utils;
A compiled regex should be even more performant, if performance is an issue I'd prefer to use regex here, making someone read through the entire tree class just to have them realize it's the same as String.endsWith doesn't sound like a great idea to me

2023-02-16 22:28 UTC, orbyfied commented on src/main/java/com/domain/redstonetools/utils/CharTreeNode.java
> +package com.domain.redstonetools.utils;
I don't think a compiled regex will be faster here.
That's practically the same as doing 5 `endsWith` calls, as you need a separate group for each literal.
I have added comments to the class though.

2023-02-16 22:32 UTC, orbyfied commented
@Matthias1590 I've implemented all changes except removing the CharTreeNode, which I documented, so it is not necessary to read through the source code anymore.

2023-02-16 22:34 UTC, Matthias1590 commented
Adding documentation doesn't mean you don't have to read the code, if you can show me that this class is a lot faster than regex we can use it tho I still don't like the unnecessary complexity it adds, readability is more important than performance in this case imo

2023-02-16 23:12 UTC, orbyfied commented
I benchmarked it, ~70% faster than regex, but it doesn't really make a big difference in this case I think, so I moved to regex as you wished.

2023-02-16 23:14 UTC, orbyfied commented
Actually now that I think about it, we might be doing this on millions of blocks at a time. If it gets noticeable I suggest we switch back to the char tree.

2023-02-17 07:25 UTC, Matthias1590 requested changes
The tree class and benchmark classes can be removed, other than that this looks great

2023-02-17 09:22 UTC, orbyfied commented
Regex doesn't seem to be working.
The filter is completely broken.

2023-02-17 09:34 UTC, orbyfied commented
I fixed the regex and removed all traces of CharTreeNode
@Matthias1590 You can merge now

2023-02-17 11:02 UTC, Matthias1590 approved these changes

2023-02-17 11:02 UTC, merged