Added MinSelection Feature
RedstoneTools/redstone-tools pull request #81
Opened 2023-02-22 13:02 UTC by RUGMJ

Closes #55

2023-03-01 15:29 UTC, Matthias1590 requested changes

2023-03-01 15:29 UTC, Matthias1590 commented on src/main/java/com/domain/redstonetools/features/commands/MinSelectionFeature.java
> +    private List<BlockVector3> makeChanges(World selectionWorld, Region selection)
Why does this return a list of vectors? Also might be nice to give this a more descriptive name

2023-03-01 15:29 UTC, Matthias1590 commented on src/main/java/com/domain/redstonetools/features/commands/MinSelectionFeature.java
> +            throw new CommandSyntaxException(new SimpleCommandExceptionType(msg), msg);
No need to pass the type, just pass null like all other features do

2023-03-01 15:29 UTC, Matthias1590 commented on src/main/java/com/domain/redstonetools/features/commands/MinSelectionFeature.java
> +        var actor = FabricAdapter.adaptPlayer(source.getPlayer());
We should probably extract the functionality to get the WE selection into some utility method and make this feature and other WE related features use that instead

2023-03-01 15:41 UTC, RUGMJ commented on src/main/java/com/domain/redstonetools/features/commands/MinSelectionFeature.java
> +    private List<BlockVector3> makeChanges(World selectionWorld, Region selection)
If you read the function you'll see that it uses it to modify the changes list

2023-03-01 15:41 UTC, RUGMJ commented on src/main/java/com/domain/redstonetools/features/commands/MinSelectionFeature.java
> +            throw new CommandSyntaxException(new SimpleCommandExceptionType(msg), msg);
Wouldn't that give a blank error message?

2023-03-01 15:42 UTC, RUGMJ commented on src/main/java/com/domain/redstonetools/features/commands/MinSelectionFeature.java
> +        var actor = FabricAdapter.adaptPlayer(source.getPlayer());
I've suggested this but I think it's out of the scope of this PR

2023-03-01 16:19 UTC, Matthias1590 commented on src/main/java/com/domain/redstonetools/features/commands/MinSelectionFeature.java
> +            throw new CommandSyntaxException(new SimpleCommandExceptionType(msg), msg);
Nope, it works fine for other features

2023-03-01 16:20 UTC, Matthias1590 commented on src/main/java/com/domain/redstonetools/features/commands/MinSelectionFeature.java
> +            throw new CommandSyntaxException(new SimpleCommandExceptionType(msg), msg);
This probably shouldn't throw a command syntax exception though, as it's not related to the user's input, a runtime exception might be better

2023-03-01 16:20 UTC, Matthias1590 commented on src/main/java/com/domain/redstonetools/features/commands/MinSelectionFeature.java
> +        var actor = FabricAdapter.adaptPlayer(source.getPlayer());
Fair

2023-03-01 16:28 UTC, RUGMJ commented on src/main/java/com/domain/redstonetools/features/commands/MinSelectionFeature.java
> +            throw new CommandSyntaxException(new SimpleCommandExceptionType(msg), msg);
> Nope, it works fine for other features

I mean to the player

2023-03-01 16:29 UTC, RUGMJ commented on src/main/java/com/domain/redstonetools/features/commands/MinSelectionFeature.java
> +            throw new CommandSyntaxException(new SimpleCommandExceptionType(msg), msg);
> This probably shouldn't throw a command syntax exception though, as it's not related to the user's input, a runtime exception might be better

I thought that too but the error is related to the selection so it kind of is the input, up to you tho

2023-03-01 16:31 UTC, RUGMJ commented on src/main/java/com/domain/redstonetools/features/commands/MinSelectionFeature.java
> +    private List<BlockVector3> makeChanges(World selectionWorld, Region selection)
> I can see that it makes changes but those changes aren't used anywhere, something like "minimizeRegion" or "removeAirLayers" makes more sense to me than "makeChanges"

ofc its used? `selection.contract(changes.toArray(new BlockVector3[changes.size()]));`

2023-03-01 16:31 UTC, RUGMJ commented on src/main/java/com/domain/redstonetools/features/commands/MinSelectionFeature.java
> +    private List<BlockVector3> makeChanges(World selectionWorld, Region selection)
renaming the function makes sense tho

2023-03-01 16:33 UTC, RUGMJ commented on src/main/java/com/domain/redstonetools/features/commands/MinSelectionFeature.java
> +        var actor = FabricAdapter.adaptPlayer(source.getPlayer());
> Fair, though generally it's good practice to abstract something away if you find yourself copy pasting it

I completely agree but this PR is for adding the minimise selection feature so modifying other features wouldn't make sense, id be happy to work on this in a separate PR after this PR is resolved

2023-03-01 16:53 UTC, Matthias1590 commented on src/main/java/com/domain/redstonetools/features/commands/MinSelectionFeature.java
> +            throw new CommandSyntaxException(new SimpleCommandExceptionType(msg), msg);
I think since it's not related to command syntax a runtime exception might be nicer here

2023-03-01 16:53 UTC, Matthias1590 commented on src/main/java/com/domain/redstonetools/features/commands/MinSelectionFeature.java
> +    private List<BlockVector3> makeChanges(World selectionWorld, Region selection)
> > I can see that it makes changes but those changes aren't used anywhere, something like "minimizeRegion" or "removeAirLayers" makes more sense to me than "makeChanges"
> 
> ofc its used? `selection.contract(changes.toArray(new BlockVector3[changes.size()]));`

The value you return isn't used

2023-03-01 17:16 UTC, RUGMJ commented on src/main/java/com/domain/redstonetools/features/commands/MinSelectionFeature.java
> +    private List<BlockVector3> makeChanges(World selectionWorld, Region selection)
> The value you return isn't used
```
    if (!finished)
            changes = makeChanges(selectionWorld, selection);
```

2023-03-01 21:49 UTC, RUGMJ commented on src/main/java/com/domain/redstonetools/features/commands/MinSelectionFeature.java
> +    private List<BlockVector3> makeChanges(World selectionWorld, Region selection)
It isn't used by the execute function but it is used in the makeChanges method itself ig it could be turned into 2 methods but it works just fine as is

2023-03-01 23:25 UTC, Matthias1590 commented on src/main/java/com/domain/redstonetools/features/commands/MinSelectionFeature.java
> +    private List<BlockVector3> makeChanges(World selectionWorld, Region selection)
it's assigned but never used there and it's never even assigned outside of the function

2023-03-01 23:33 UTC, RUGMJ commented on src/main/java/com/domain/redstonetools/features/commands/MinSelectionFeature.java
> +    private List<BlockVector3> makeChanges(World selectionWorld, Region selection)
> it's assigned but never used there and it's never even assigned outside of the function

The function will try to minimise the selection, if it couldn't then it is deemed finished so it returns the changes it was given, if not it will call itself with the changes it was given this loops until the selection is fully minimised, there could be a count added which if higher than x the function immediately returns null but after extensive testing this is not needed

2023-03-01 23:38 UTC, Matthias1590 commented on src/main/java/com/domain/redstonetools/features/commands/MinSelectionFeature.java
> +    private List<BlockVector3> makeChanges(World selectionWorld, Region selection)
I'm not questioning the implementation, I'm saying that the return value isn't used and so the method may as well return void, this would keep the signature cleaner and the code simpler

2023-03-01 23:41 UTC, RUGMJ commented on src/main/java/com/domain/redstonetools/features/commands/MinSelectionFeature.java
> +    private List<BlockVector3> makeChanges(World selectionWorld, Region selection)
> I'm not questioning the implementation, I'm saying that the return value isn't used and so the method may as well return void, this would keep the signature cleaner and the code simpler

But the method calls itself and assigns a variable so returning void would break it

2023-03-01 23:41 UTC, RUGMJ commented on src/main/java/com/domain/redstonetools/features/commands/MinSelectionFeature.java
> +    private List<BlockVector3> makeChanges(World selectionWorld, Region selection)
so doing what youre asking would require the implementation changing

2023-03-01 23:43 UTC, Matthias1590 commented on src/main/java/com/domain/redstonetools/features/commands/MinSelectionFeature.java
> +    private List<BlockVector3> makeChanges(World selectionWorld, Region selection)
> > I'm not questioning the implementation, I'm saying that the return value isn't used and so the method may as well return void, this would keep the signature cleaner and the code simpler
> 
> But the method calls itself and assigns a variable so returning void would break it

then don't assign a variable to it, the value isn't used anyway

2023-03-01 23:44 UTC, RUGMJ commented on src/main/java/com/domain/redstonetools/features/commands/MinSelectionFeature.java
> +    private List<BlockVector3> makeChanges(World selectionWorld, Region selection)
but the value is used, its used to actually modify the selection

2023-03-01 23:56 UTC, Matthias1590 commented on src/main/java/com/domain/redstonetools/features/commands/MinSelectionFeature.java
> +    private List<BlockVector3> makeChanges(World selectionWorld, Region selection)
> but the value is used, its used to actually modify the selection

it's not, when you reassign changes you're not reassigning selection

2023-03-01 23:56 UTC, DiamondTaco commented on src/main/java/com/domain/redstonetools/features/commands/MinSelectionFeature.java
> +    private List<BlockVector3> makeChanges(World selectionWorld, Region selection)
matthias the variable is assigned and returned in the function bc its recursive

2023-03-01 23:57 UTC, Matthias1590 commented on src/main/java/com/domain/redstonetools/features/commands/MinSelectionFeature.java
> +    private List<BlockVector3> makeChanges(World selectionWorld, Region selection)
> matthias the variable is assigned and returned in the function bc its recursive

the value isn't used outside of the method so I don't see why it should return anything at all

2023-03-02 00:02 UTC, RUGMJ commented on src/main/java/com/domain/redstonetools/features/commands/MinSelectionFeature.java
> +    private List<BlockVector3> makeChanges(World selectionWorld, Region selection)
> > but the value is used, its used to actually modify the selection
> 
> it's not, when you reassign changes you're not reassigning selection

but it is here `selection.contract(changes.toArray(new BlockVector3[changes.size()]));`

2023-03-02 00:02 UTC, RUGMJ commented on src/main/java/com/domain/redstonetools/features/commands/MinSelectionFeature.java
> +    private List<BlockVector3> makeChanges(World selectionWorld, Region selection)
> > matthias the variable is assigned and returned in the function bc its recursive
> 
> the value isn't used outside of the method so I don't see why it should return anything at all

Which is why I suggested a 2nd method which is void and wraps the other one tho this just makes things more confusing

2023-03-02 00:04 UTC, Matthias1590 commented on src/main/java/com/domain/redstonetools/features/commands/MinSelectionFeature.java
> +    private List<BlockVector3> makeChanges(World selectionWorld, Region selection)
> > > but the value is used, its used to actually modify the selection
> > 
> > it's not, when you reassign changes you're not reassigning selection
> 
> but it is here `selection.contract(changes.toArray(new BlockVector3[changes.size()]));`

yes, I know the changes variable is used inside of the method but it isn't used after the last assignment so both the last assignment and return statements can be removed

2023-03-02 00:10 UTC, RUGMJ commented on src/main/java/com/domain/redstonetools/features/commands/MinSelectionFeature.java
> +    private List<BlockVector3> makeChanges(World selectionWorld, Region selection)
But they cant because the function loops itself so that it can minimise it completely, although the return isnt used on the first instance of the function it is used on the rest

2023-03-02 00:11 UTC, DiamondTaco commented on src/main/java/com/domain/redstonetools/features/commands/MinSelectionFeature.java
> +    private List<BlockVector3> makeChanges(World selectionWorld, Region selection)
matthias, it's a recursive function. the return value is used within itself to shrink the selection.

2023-03-02 00:12 UTC, RUGMJ commented on src/main/java/com/domain/redstonetools/features/commands/MinSelectionFeature.java
> +    private List<BlockVector3> makeChanges(World selectionWorld, Region selection)
> matthias, it's a recursive function. the return value is used within itself to shrink the selection.

Thanks ive been trying to put it into concise words like that

2023-03-02 06:40 UTC, Matthias1590 commented on src/main/java/com/domain/redstonetools/features/commands/MinSelectionFeature.java
> +    private List<BlockVector3> makeChanges(World selectionWorld, Region selection)
that's not how recursion works, you're not using the return value, try replacing the last assignment with just a call and remove the return statement, it'll work the exact same

2023-03-03 16:57 UTC, RUGMJ commented on src/main/java/com/domain/redstonetools/features/commands/MinSelectionFeature.java
> +            throw new CommandSyntaxException(new SimpleCommandExceptionType(msg), msg);
> I think since it's not related to command syntax a runtime exception might be nicer here

Shouldnt it be a CommandException like ive changed it to? I thought thats what you meant? Or do you mean the java runtime exception

2023-03-03 17:12 UTC, Matthias1590 commented on src/main/java/com/domain/redstonetools/features/commands/MinSelectionFeature.java
> +            throw new CommandSyntaxException(new SimpleCommandExceptionType(msg), msg);
CommandException works too I guess

2023-03-03 17:12 UTC, Matthias1590 approved these changes

2023-03-03 17:13 UTC, merged