Revise ColorCode
RedstoneTools/redstone-tools pull request #95
Opened 2023-02-27 21:09 UTC by DiamondTaco

I merged into the wrong branch at first

2023-02-27 21:18 UTC, MiranCZ commented
You can just change that

2023-02-27 21:23 UTC, MiranCZ commented
Yeah, when you click the same edit button, you can change the branch

2023-02-28 06:07 UTC, MiranCZ commented
Why do you want to access it outside the class? It should be `public static` to do that tho

2023-02-28 06:09 UTC, DiamondTaco commented
> Why do you want to access it outside the class? It should be `public static` to do that tho

:facepalm: yeah, you're right. Matthias asked for it specifically on the issue.

2023-02-28 06:34 UTC, Matthias1590 commented
> > Why do you want to access it outside the class? It should be `public static` to do that tho
> 
> :facepalm: yeah, you're right. Matthias asked for it specifically on the issue.

moving them to a utils class might be cleaner

2023-02-28 06:35 UTC, Matthias1590 requested changes
Move utility functions to a utils class and turn color into an enum

2023-02-28 12:41 UTC, DiamondTaco commented
> 

done

2023-02-28 20:57 UTC, DiamondTaco commented
> Move utility functions to a utils class and turn color into an enum

done

2023-03-01 15:09 UTC, Matthias1590 requested changes

2023-03-01 15:09 UTC, Matthias1590 commented on src/main/java/com/domain/redstonetools/utils/ColorUtils.java
> +    public static final HashMap<String, Pair<String, String>> blockMap = new HashMap<>();
This doesnt need to be public

2023-03-01 15:09 UTC, Matthias1590 commented on src/main/java/com/domain/redstonetools/utils/ColorUtils.java
> +    public static Pair<String, String> getColorFromBlockId(String blockId) {
Why does this return a pair and not a color like the method name suggests?

2023-03-01 15:09 UTC, Matthias1590 commented on src/main/java/com/domain/redstonetools/utils/ColorUtils.java
> +    public enum Colors {
Maybe move this to the block color argument file and rename to "Color", also the blockColor argument should probably use this enum instead of strings

2023-03-01 17:57 UTC, DiamondTaco commented on src/main/java/com/domain/redstonetools/utils/ColorUtils.java
> +    public static Pair<String, String> getColorFromBlockId(String blockId) {
I'll rename it

2023-03-01 17:58 UTC, DiamondTaco commented on src/main/java/com/domain/redstonetools/utils/ColorUtils.java
> +    public static final HashMap<String, Pair<String, String>> blockMap = new HashMap<>();
done

2023-03-01 17:58 UTC, DiamondTaco commented on src/main/java/com/domain/redstonetools/utils/ColorUtils.java
> +    public enum Colors {
I think it should stay in ColorUtils, but i made BlockColorArgumentType use it

2023-03-01 23:37 UTC, Matthias1590 requested changes

2023-03-01 23:37 UTC, Matthias1590 commented on src/main/java/com/domain/redstonetools/features/arguments/BlockColorArgumentType.java
>  public class BlockColorArgumentType extends SetArgumentType<String> {
this might as well extend SetArgumentType<Color>

2023-03-01 23:39 UTC, DiamondTaco commented on src/main/java/com/domain/redstonetools/features/arguments/BlockColorArgumentType.java
>  public class BlockColorArgumentType extends SetArgumentType<String> {
> 

wdym?

2023-03-01 23:41 UTC, Matthias1590 commented on src/main/java/com/domain/redstonetools/features/arguments/BlockColorArgumentType.java
>  public class BlockColorArgumentType extends SetArgumentType<String> {
The block color argument type should give you a color instead of a string

2023-03-01 23:45 UTC, DiamondTaco commented on src/main/java/com/domain/redstonetools/features/arguments/BlockColorArgumentType.java
>  public class BlockColorArgumentType extends SetArgumentType<String> {
> The block color argument type should give you a color instead of a string



> The block color argument type should give you a color instead of a string

i see, the line of code you highlighted was throwing me off

2023-03-01 23:47 UTC, DiamondTaco commented on src/main/java/com/domain/redstonetools/features/arguments/BlockColorArgumentType.java
>  public class BlockColorArgumentType extends SetArgumentType<String> {
i tried adding that and it breaks tab autocomplete, all the color names are capitalized

2023-03-02 17:37 UTC, DiamondTaco commented
Can this get merged?

2023-03-02 18:45 UTC, Matthias1590 commented on src/main/java/com/domain/redstonetools/features/arguments/BlockColorArgumentType.java
>  public class BlockColorArgumentType extends SetArgumentType<String> {
I don't see why it wouldn't be possible though

2023-03-02 19:03 UTC, DiamondTaco commented
> Once the block color arg type returns a color I'll merge

I can do it, but then all the names while running the command are capitalized, and autocomplete breaks. Not having tab autocomplete for this feature would be a serious downgrade.

2023-03-02 19:46 UTC, Matthias1590 commented
> > Once the block color arg type returns a color I'll merge
> 
> I can do it, but then all the names while running the command are capitalized, and autocomplete breaks. Not having tab autocomplete for this feature would be a serious downgrade.

Why are they capitalized and can they not be capitalized? Sounds like a simple bug with a simple fix

2023-03-03 17:23 UTC, DiamondTaco commented
> > > Once the block color arg type returns a color I'll merge
> > 
> > 
> > I can do it, but then all the names while running the command are capitalized, and autocomplete breaks. Not having tab autocomplete for this feature would be a serious downgrade.
> 
> Why are they capitalized and can they be not capitalized? Sounds like a simple bug with a simple fix

The reason they are capitalized is the enum variants are capitalized, so brigadier picks them up as capitalized. The only way I know how to fix this would be to fully lowercase all of the color variants, which goes against constant naming conventions. IDK which option to choose tbh.

2023-03-03 17:24 UTC, MiranCZ commented
Can't you just `do.toString().toLowerCase()`?

2023-03-03 17:25 UTC, DiamondTaco commented
> Can't you just `do.toString().toLowerCase()`?

its handled by mojang's library, so i can't do anything about it.

2023-03-03 18:17 UTC, DiamondTaco commented
> > Can't you just `do.toString().toLowerCase()`?
> 
> its handled by mojang's library, so i can't do anything about it.

nvm im an idiot i can just override toString on the enum

2023-03-03 18:23 UTC, DiamondTaco commented
> Once the block color arg type returns a color I'll merge

done

2023-03-03 18:25 UTC, DiamondTaco commented on src/main/java/com/domain/redstonetools/features/arguments/BlockColorArgumentType.java
>  public class BlockColorArgumentType extends SetArgumentType<String> {
done

2023-03-03 20:07 UTC, Matthias1590 requested changes

2023-03-03 20:07 UTC, Matthias1590 commented on src/main/java/com/domain/redstonetools/features/commands/ColorCodeFeature.java
> +    private boolean shouldBeColored(World world, BlockVector3 pos, String onlyColor) {
Why is onlyColor a string? I think it'd make more sense to use the Color enum everywhere as opposed to converting it to a string in some places

2023-03-03 20:09 UTC, DiamondTaco commented on src/main/java/com/domain/redstonetools/features/commands/ColorCodeFeature.java
> +    private boolean shouldBeColored(World world, BlockVector3 pos, String onlyColor) {
It is being compared against the matched block-id's which are strings. it doesn't really matter tbh

2023-03-03 20:11 UTC, Matthias1590 commented on src/main/java/com/domain/redstonetools/features/commands/ColorCodeFeature.java
> +    private boolean shouldBeColored(World world, BlockVector3 pos, String onlyColor) {
they should be converted only when comparing, passing them around as strings is more error prone

2023-03-03 20:11 UTC, DiamondTaco commented on src/main/java/com/domain/redstonetools/features/commands/ColorCodeFeature.java
> +    private boolean shouldBeColored(World world, BlockVector3 pos, String onlyColor) {
There's no bugs in the code tho

2023-03-03 20:12 UTC, Matthias1590 commented on src/main/java/com/domain/redstonetools/features/commands/ColorCodeFeature.java
> +    private boolean shouldBeColored(World world, BlockVector3 pos, String onlyColor) {
That doesn't mean much, code shouldn't be error prone, enums are perfect for things like this, there's no reason to pass around strings

2023-03-03 20:13 UTC, DiamondTaco commented on src/main/java/com/domain/redstonetools/features/commands/ColorCodeFeature.java
> +    private boolean shouldBeColored(World world, BlockVector3 pos, String onlyColor) {
pushed

2023-03-03 20:13 UTC, DiamondTaco commented on src/main/java/com/domain/redstonetools/features/commands/ColorCodeFeature.java
> +    private boolean shouldBeColored(World world, BlockVector3 pos, String onlyColor) {
> That doesn't mean much, code shouldn't be error prone, enums are perfect for things like this, there's no reason to pass around strings

srry i just got a little annoyed

2023-03-03 20:14 UTC, Matthias1590 commented on src/main/java/com/domain/redstonetools/features/commands/ColorCodeFeature.java
> +    private boolean shouldBeColored(World world, BlockVector3 pos, String onlyColor) {
Thanks

2023-03-03 20:16 UTC, DiamondTaco commented
why closed?

2023-03-03 20:17 UTC, MiranCZ commented
> why closed?

Good question

2023-03-03 20:17 UTC, merged